---
- ros_topic_name: "/reached_pose"
  gz_topic_name: "/model/DeliveryBot/reached_pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS
- ros_topic_name: "/cmd_pose"
  gz_topic_name: "/model/DeliveryBot/cmd_pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: ROS_TO_GZ
- ros_topic_name: "/pose"
  gz_topic_name: "/model/DeliveryBot/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
