name: Build and test the VDA5050 library

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  industrial_ci:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        distro: [humble, jazzy]
        compiler: [gcc, clang]
    env:
      ISOLATION: "shell"
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.distro }}-ros-core
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update -qq -y
          apt-get install libpaho-mqtt-dev libpaho-mqttpp-dev libfmt-dev mosquitto -qq -y
      - name: Start MQTT broker
        run: |
          mosquitto -d
          sleep 2  # Wait for broker to start

      # GCC
      - if: ${{ matrix.compiler == 'gcc' }}
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          UPSTREAM_WORKSPACE: 'github:sauk2/vda5050_interfaces#throwaway/temp'
          TARGET_CMAKE_ARGS: '-DENABLE_ROS2=ON'

      # Clang
      - if: ${{ matrix.compiler == 'clang' }}
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          UPSTREAM_WORKSPACE: 'github:sauk2/vda5050_interfaces#throwaway/temp'
          ADDITIONAL_DEBS: clang lld
          CC: "clang"
          CXX: "clang++"
          TARGET_CMAKE_ARGS: '-DENABLE_ROS2=ON'
